# -*- coding: utf-8 -*-
"""Resume_Analyzer_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fjD7Dg2Ma5G-JFXlgdVGBzpuLgJjVlWv
"""

# Install required libraries (run once)
!pip install pypdf python-docx

from pypdf import PdfReader
from docx import Document
import os

# 👉 Paste your file path here
file_path = "/content/Ushasree_Resume.pdf"   # change this

# ---------- TEXT EXTRACTION ----------
def extract_text(file_path):
    text = ""

    try:
        if file_path.endswith(".pdf"):
            reader = PdfReader(file_path)
            for page in reader.pages:
                text += page.extract_text() or ""

        elif file_path.endswith(".txt"):
            with open(file_path, "r", encoding="utf-8") as f:
                text = f.read()

        elif file_path.endswith(".docx"):
            doc = Document(file_path)
            for para in doc.paragraphs:
                text += para.text + "\n"

        else:
            text = "Unsupported file format"

    except Exception as e:
        text = f"Error reading file: {e}"

    return text


# ---------- ANALYSIS ----------
def analyze_resume(resume_text):
    keywords = [
        "python", "java", "machine learning", "data structures",
        "html", "sql", "c", "c++", "css", "cloud", "networking"
    ]

    resume_text = resume_text.lower()

    found_skills = []
    missing_skills = []

    for word in keywords:
        if word in resume_text:
            found_skills.append(word)
        else:
            missing_skills.append(word)

    score = len(found_skills) * 10

    return score, found_skills, missing_skills


# ---------- SUGGESTIONS ----------
def give_suggestions(score, missing_skills):
    print("\n--- Suggestions ---")

    if score >= 60:
        print("✅ Your resume is strong. Consider adding advanced projects or certifications.")
    elif score >= 30:
        print("⚠️ Your resume is average. Improve by adding more skills and projects.")
    else:
        print("❌ Your resume needs improvement. Focus on building skills and projects.")

    print("\n💡 Recommended Skills to Add:")
    for skill in missing_skills[:5]:  # show top 5 missing
        print("-", skill)


# ---------- MAIN ----------
if not os.path.exists(file_path):
    print("❌ File not found. Check the path.")
else:
    resume = extract_text(file_path)

    print("\n--- Resume Preview ---\n")
    print(resume[:1000])

    score, found, missing = analyze_resume(resume)

    print("\n--- Analysis Result ---")
    print("Score:", score, "/ 100")

    print("\nSkills Found:")
    for skill in found:
        print("-", skill)

    print("\nMissing Skills:")
    for skill in missing:
        print("-", skill)

    give_suggestions(score, missing)